apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: k8s-home
  labels:
    app: prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: nginx
          imagePullPolicy: IfNotPresent
 