apiVersion: v1
data:
  automations.yaml: |-
    # - - - - - - - - - - - - - - - - - - - -
    #    Time Based
    # - - - - - - - - - - - - - - - - - - - -
    - alias: Samuel's Bedtime
      trigger:
      - at: '20:00:00'
        platform: time
      action:
        entity_id: light.samuels_light
        service: light.turn_off

    - alias: Electric Blanket On
      action:
        entity_id: switch.electric_blanket
        service: switch.turn_on
      trigger:
      - at: '22:30:00'
        platform: time

    - alias: Electric Blanket Off
      action:
        entity_id: switch.electric_blanket
        service: switch.turn_off
      trigger:
      - at: '23:10:00'
        platform: time

    # - - - - - - - - - - - - - - - - - - - -
    #    Presence Based
    # - - - - - - - - - - - - - - - - - - - -
    - alias: Turn Off Lights on Leaving
      trigger:
        - entity_id: group.all_devices
          platform: state
          to: not_home
      condition: []
      action:
        - data:
            entity_id: group.all_lights
          service: light.turn_off

    - alias: Turn On Lights on Arrival
      trigger:
        - entity_id: group.all_devices
          platform: state
          to: home
      condition:
        - after: sunset
          after_offset: -01:00:00
          condition: sun
      action:
        - data:
            entity_id: group.all_lights
          service: light.turn_off

    - alias: Alert when Chris arrives home
      trigger:
        - platform: state
          entity_id: device_tracker.chrismobile
          to: home
      condition:
        - condition: state
          entity_id: input_boolean.voice_alerts
          state: 'on'
      action:
        - service: tts.google_say
          data:
            entity_id: media_player.living_room_speaker
            message: 'Chris has arrived home'

    - alias: Alert when Jo arrives home
      trigger:
        - platform: state
          entity_id: device_tracker.chrismobile
          to: home
      condition:
        - condition: state
          entity_id: input_boolean.voice_alerts
          state: 'on'
      action:
        - service: tts.google_say
          data:
            entity_id: media_player.living_room_speaker
            message: 'Joanne has arrived home'
  configuration.yaml: |-
    # - - - - - - - - - - - - - - - - - - - -
    #    Core Configuration
    # - - - - - - - - - - - - - - - - - - - -
    homeassistant:
      name: Home
      latitude: 51.98781
      longitude: -0.18835
      elevation: 0
      unit_system: metric
      time_zone: Europe/London
      # Customization file
      #customize: !include customize.yaml

    sun:

    # - - - - - - - - - - - - - - - - - - - -
    #    Core Enables
    # - - - - - - - - - - - - - - - - - - - -
    http:
      api_password: !secret http_password
      base_url: hass.home.evns.io

    # Enable frontend and configuration panels
    frontend:
    config:

    # Discover some devices automatically
    discovery:

    # Allows you to issue voice commands from the frontend in enabled browsers
    conversation:

    # Enables support for tracking state changes over time
    history:

    # View all events in a logbook
    logbook:

    # Text to speech
    tts:
      - platform: google

    # - - - - - - - - - - - - - - - - - - - -
    #    Extras
    # - - - - - - - - - - - - - - - - - - - -

    # MQTT Broker
    mqtt:
      broker: 192.168.0.101
      port: 1883

    # Google Assistant
    google_assistant:
      project_id: !secret google-project
      client_id: !secret google-client_id
      access_token: !secret google-access_token
      api_key: !secret google-api_key
      exposed_domains:
        - switch
        - light
        - group

    # Chromecast
    media_player:
      - platform: cast
        host: 192.168.0.110 # fixed ip set by router
      - platform: cast
        host: 192.168.0.111 # fixed ip set by router

    # Sky Hub Device Tracker
    device_tracker:
      - platform: sky_hub
        host: 192.168.0.1
        track_new_devices: no

    # - - - - - - - - - - - - - - - - - - - -
    #    Includes
    # - - - - - - - - - - - - - - - - - - - -

    input_boolean: !include input_boolean.yaml
    switch: !include switch.yaml
    light: !include light.yaml
    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
  groups.yaml: |-
    # Entity Groups
    living_room:
      name: "Living Room"
      view: yes
      entities:
        - light.living_room_alcove
        - light.living_room_side_light
        - switch.test_device
        - media_player.living_room_tv
        - media_player.living_room_speaker
    main_bedroom:
      name: "Main Bedroom"
      view: yes
      entities:
        - switch.electric_blanket
        - media_player.bedroom_tv
    samuel_bedroom:
      name: "Samuel's Bedroom"
      view: yes
      entities:
        - light.samuels_light
  input_boolean.yaml: |-
    voice_alerts:
        name: Voice Alerts
        initial: on
  known_devices.yaml: |-
    jo-mobile:
      hide_if_away: false
      icon:
      mac: D4:63:C6:72:74:ED
      name: Joanne
      picture:
      track: true
      vendor: Motorola Mobility LLC, a Lenovo Company
    chris-mobile:
      hide_if_away: false
      icon:
      mac: 94:65:2D:C9:71:FF
      name: Chris
      picture:
      track: true
      vendor: unknown
  light.yaml: |-
    # Light definitions
    - platform: mqtt
      name: "Living Room Alcove"
      state_topic: "stat/livingroom/alcovelight/POWER"
      command_topic: "cmnd/livingroom/alcovelight/POWER"
      retain: true
    - platform: mqtt
      name: "Living Room Side Light"
      state_topic: "stat/livingroom/sidelight/POWER"
      command_topic: "cmnd/livingroom/sidelight/POWER"
      retain: true
    - platform: mqtt
      name: "Samuel's Light"
      state_topic: "stat/samuelsroom/lamp/POWER"
      command_topic: "cmnd/samuelsroom/lamp/POWER"
      retain: true
  scripts.yaml: ""
  sensor.yaml: |-
    - platform: mqtt
      state_topic: "home/livingroom/temperature"
      name: "Living Room Temperature"
      unit_of_measurement: '°C'
    - platform: mqtt
      state_topic: "home/livingroom/humidity"
      name: "Living Room Humidity"
      unit_of_measurement: '%'
  switch.yaml: |-
    # Switch definitions
    - platform: mqtt
      name: "Test Device"
      state_topic: "stat/livingroom/testdevice/POWER"
      command_topic: "cmnd/livingroom/testdevice/POWER"
      retain: true
    - platform: mqtt
      name: "Electric Blanket"
      state_topic: "stat/bedroom/blanket/POWER"
      command_topic: "cmnd/bedroom/blanket/POWER"
      retain: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: hass-config
