# Views (tabs)
default_view:
  view: yes
  entities:
    - sensor.living_room_temperature
    - sensor.living_room_humidity
    - group.downstairs_devices
    - group.upstairs_devices
    - group.controls
    - device_tracker.chrismobile
    - device_tracker.jomobile

living_room:
  name: "Living Room"
  view: yes
  entities:
    - light.living_room_alcove
    - light.living_room_side_light
    - switch.test_device
    - media_player.living_room_tv
    - media_player.living_room_speaker

main_bedroom:
  name: "Main Bedroom"
  view: yes
  entities:
    - switch.electric_blanket
    - media_player.bedroom_tv

samuel_bedroom:
  name: "Samuel's Bedroom"
  view: yes
  entities:
    - light.samuels_light

# Cards
downstairs_devices:
  name: Downstairs
  entities:
    - light.living_room_alcove
    - light.living_room_side_light

upstairs_devices:
  name: Upstairs
  entities:
    - switch.electric_blanket

controls:
  name: Controls
  entities:
    - input_boolean.voice_alerts